# Site settings
title: Maths and Stuff
email: EvansJA8@Cardiff.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Hopefully this blog will end up being full of interesting mathematics, 
  first year follies and updates on current postgraduate interests.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: davehedgehog05
github_username:  JamesEvans2014

# Build settings
markdown: kramdown
